### ISSUE TITLE
Fixed header is tripping over Unified review

### ISSUE THREAD

**Issue by jetersen** [StylishThemes/GitHub-FixedHeader#10]
Using Refined Github and Dark Theme, I get the following on unified.
![image](https://user-images.githubusercontent.com/1661688/31984215-ed1ab774-b960-11e7-864f-ae55969fd8a5.png)

**Comment by Mottie** [comment]
Hi @casz!

I'm pretty sure I fixed this issue. Please make sure you have the most recent update of this style.

If not, please let me know which browser and page you're seeing this on. Do you have to be a reviewer, author or anyone to see this problem?

**Comment by jetersen** [comment]
![image](https://user-images.githubusercontent.com/1661688/31998671-eafecb4e-b990-11e7-9851-af675c066be3.png)
Already updated

**Comment by jetersen** [comment]
It's fixed for most but not for the first element 👎 
https://github.com/fastlane/fastlane/pull/10690/files?diff=unified

Chrome Version 61.0.3163.100... oops UPDATING
Updated: Chrome Version 62.0.3202.62 (Official Build) (64-bit)
Still the same
First element bugged:
![image](https://user-images.githubusercontent.com/1661688/31998789-5182b510-b991-11e7-8ad9-c3deab04f6eb.png)
Second element not bugged:
![image](https://user-images.githubusercontent.com/1661688/31998815-646c65ea-b991-11e7-9073-8fd4b49b1177.png)

**Comment by jetersen** [comment]
@Mottie I tried adding some style and found something interesting 👍 
padding-bottom: 50px;
![image](https://user-images.githubusercontent.com/1661688/31999598-2905ce08-b994-11e7-915d-5f332328d7d8.png)

**Comment by Mottie** [comment]
That is odd... I don't think Refined GitHub is adding that inline style. And we surely aren't with a css style.

I still can't duplicate the issue... I do see the first header content shift over in Firefox after hovering over the sticky header a few times; it's not consistent and seems impossible to fix. I believe that's a Firefox bug. But I can't reproduce this issue in Chrome. Did you also update GitHub-Dark?

**Comment by jetersen** [comment]
Yup updated and all :|

**Comment by jetersen** [comment]
![image](https://user-images.githubusercontent.com/1661688/32021012-5c07c188-b9d2-11e7-9f92-412f1991cdc2.png)
Using GitHub Dark user script :| So always updated

**Comment by jetersen** [comment]
Aha... Installing GitHub Dark from userstyles does not cause it to bug 👍

**Comment by jetersen** [comment]
I assume it's the GitHub Dark Settings item messing with it.

**Comment by Mottie** [comment]
Oh you mean it's the GitHub-Dark script?

**Comment by jetersen** [comment]
Yes 👍

**Comment by Mottie** [comment]
Hehe, sorry for not following up... Is this still an issue. I haven't seen this glitch, so I'm guessing it isn't a problem anymore?

**Comment by jetersen** [comment]
@Mottie yup
![image](https://user-images.githubusercontent.com/1661688/33231504-932db154-d1f6-11e7-9207-e1b919f4b5cc.png)

**Comment by jetersen** [comment]
It's definitely caused by a mixture of GitHub Dark script and Fixed header. I tried disabling AutoComplete search and Refined GitHub.

![image](https://user-images.githubusercontent.com/1661688/33231542-0d9e81de-d1f7-11e7-8e4a-012046acf742.png)

![image](https://user-images.githubusercontent.com/1661688/33231536-fb83fa10-d1f6-11e7-8cb2-f87d22ed15ae.png)

![image](https://user-images.githubusercontent.com/1661688/33231531-e735e0aa-d1f6-11e7-8bb8-bfdcc31bc1c4.png)

![image](https://user-images.githubusercontent.com/1661688/33231526-d9c32d60-d1f6-11e7-96c9-bb3a9ca3676e.png)

**Comment by Mottie** [comment]
Would you please share a link to that diff page.

**Comment by jetersen** [comment]
https://github.com/jenkinsci/office-365-connector-plugin/pull/41/files?diff=unified

**Comment by jetersen** [comment]
Really it's any pull request using unified, and only effects the first file diff element 😐

**Comment by Mottie** [comment]
So weird... now I know why I wasn't seeing this problem. I had [GitHub Diff Files Filter](https://github.com/Mottie/GitHub-userscripts/wiki/GitHub-diff-files-filter) installed - it doesn't add any css either!

I'll keep investigating.

**Comment by Mottie** [comment]
Please test v1.1.17 and let me know if everything is working...

Just to note, I ended up adding a `.js-diff-progressive-container:before` block with a height of `50px`. It has a big gap there, but it was the best method I could find to fix the issues... The other method involved making the first header 60px in height and did not look good.

**Comment by jetersen** [comment]
@Mottie it is not pretty 😐 but it fixes the issue 👍

**Comment by Mottie** [comment]
The best alternative is to install the GitHub Diff Files Filter userscript 😉

**Comment by Mottie** [comment]
Should be all fixed now... no extra padding.
